version: "3"
services:
  mongodb:
    container_name: gem-mongodb2
    image: mongo
    restart: always
    ports:
      - "27031:27017"
    networks:
      - default-network
    volumes:
      - ./backend/mongo-backup:/data/db
    environment:
      - MONGO_INITDB_DATABASE=bids_database

  backend:
    container_name: gem_backend
    image: ghcr.io/ashish8800/gem_backend:latest
    networks:
      - default-network
      - gem_frontend-network
    depends_on:
      - mongodb
    restart: on-failure
    env_file:
      - backend/.env
#    environment:
#      - MONGO_URL=mongodb://mongodb:27017/bids_database

    ports:
      - "5010:5008"

  frontend:
    container_name: gem_frontend
    image: ghcr.io/ashish8800/gem_frontend:latest
    networks:
      - gem_frontend-network
    depends_on:
      - backend
    restart: on-failure
    ports:
      - "3109:3107"

networks:
  default-network:
  gem_frontend-network:
